Added some safety checks
timelyart/Kairos pull request #76
Opened 2022-10-02 13:38 UTC by mrcrdwd

Sometimes the properties tab wouldn't load and cause the backtest to crash.

@timelyart how could we force a retry for the symbol when a the export has failed?

2022-10-02 15:01 UTC, timelyart commented
Unfortunately, this is one of the big draw backs of using Kairos instead of using some kind of API and storing your own data and coding your own indicators as there is no guarantee that (parts of) a website will load (correctly). In the past, I got worse performance on Sunday. Really long backtests (double digit hours) may fail as a session may expire/reset after a certain amount of time. 

Storing the state (and resulting data) of a backtest and then being able to restore the state within the same/new run of Kairos is definitely something I would love to have. It requires quite a bit of work and probably would introduce the use of a relational database as well.

2022-10-02 18:39 UTC, mrcrdwd commented
Makes sense. That there is no way to know for sure if an element has fully loaded. But is there a way to trigger a retry on a symbol when the reading of an element has failed?

By the way, I have an alternative for getting the currency value from the list of trades rather than the properties tab. That eliminates one interaction as you said and speeds the backtest up. But it feels hackier to get it from the list trades.

2022-10-14 15:01 UTC, timelyart requested changes
Try using: `find_elements(browser, '//button[@aria-controls="id_Symbol-info"]//span[contains(text(), "Currency")]//following::span', By.XPATH)[0].text[:-1]`

It is a wrapper  method where you can force an exception on a timeout which in turn would force a retry. The wrapper method also allows you to set a timeout limit. No need to add a separate `time.sleep`. 
Also, I'd kindly ask you to restore `log.info` to `log.debug` .

2022-10-15 07:24 UTC, timelyart approved these changes

2022-10-15 07:29 UTC, merged